### ISSUE TITLE
[Mechanics] - hole misalignment in camera mount/battery holder

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#70] opened 2021-11-26 16:32 UTC
Some misalignment here:
![image](https://user-images.githubusercontent.com/5435954/143609985-890a5802-8200-4758-8c2b-f57d21a8481b.png)
![image](https://user-images.githubusercontent.com/5435954/143610006-ad0b7621-c043-4005-b172-c1b09fe34b9b.png)

**Comment by erkiveevali** [comment] 2021-11-29 13:41
Misalignment fixed now. Was probably caused by adding the rounded corner, which caused the hole to shift.

**Closed** 2021-11-30 19:04 UTC
Labels: mechanics
